theme: minima

# Build settings
# baseurl: "" # the subpath of your site, e.g. /~you/yourrepo
# url: "" # the URL of your site, e.g. http://example.com
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
